project_id = "gjfbxqsjxasubvnpeeie"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
enabled = true
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
port = 54323
ip_version = "ipv4"

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54325
smtp_port = 54326
pop3_port = 54327

[functions]
enabled = true
region = "us-east-1"

[functions.tiktok-start]
verify_jwt = false

[functions.tiktok-callback]
verify_jwt = false

[functions.tiktok-sync]
verify_jwt = false

[functions.analytics-kpis]
verify_jwt = true

[functions.analytics-trend]
verify_jwt = true

[functions.analytics-heatmap]
verify_jwt = true

[functions.analytics-top-posts]
verify_jwt = true

[functions.insights-generate]
verify_jwt = true

[functions.report-generate]
verify_jwt = true

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_email_confirmations = false
enable_email_autoconfirm = true
enable_phone_confirmations = false
enable_phone_autoconfirm = true
